Repository d3b-center/handbook, pull requests merged in 2020-01, with the labels that each got.

#1 📝 Add products category
  docs/products/about.md
  docs/products/srs.md
  website/i18n/en.json
  website/sidebars.json
  website/siteConfig.js
Labels: documentation

#5 📝 Add projects category
  docs/projects/about.md
  website/i18n/en.json
  website/sidebars.json
  website/siteConfig.js
Labels: documentation, project

#10 📝 Add blocks for products/projects
  website/pages/en/index.js
  website/static/css/custom.css
Labels: documentation

#11 ✏️ Update wording from "the Center" to D3b
  README.md
  docs/units/adapt/about.md
  docs/units/adapt/teams/dataeng.md
  docs/units/adapt/teams/dataops.md
  docs/units/adapt/teams/devops.md
  website/pages/en/index.js
  website/siteConfig.js
Labels: documentation

#13 ✨Add product page for Clinical Data Flow
  docs/products/cdf.md
  website/i18n/en.json
  website/sidebars.json
Labels: feature, product
